# Generated by Django 5.2.1 on 2025-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
    ]
