# Generated by Django 5.2.1 on 2025-05-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_alter_meeting_status'),
    ]

    operations = [
    ]
