# Generated by Django 5.2.1 on 2025-05-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_add_expired_status'),
        ('meetings', '0007_auto_20250524_0625'),
    ]

    operations = [
    ]
